name: CI

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: windows-2016
          - host: windows-2019
          - host: windows-2022
    name: hi
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Command
        run: |
          Get-WmiObject -Query "Select Name,readtransfercount,processid from Win32_PROCESS"
