name: CI

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-11
          - host: macos-10.15
          - host: macos-12
    name: hi
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Install
        run: |
          md5sum $(which nettop)
          md5sum $(which ls)
